# This file is generated by gyp; do not edit.

export builddir_name ?= /home/animesh/Desktop/A/breakpad/src/src/client/windows/unittests/out
.PHONY: all
all:
	$(MAKE) -C ../../.. processor_bits client_tests
