# This file is generated by gyp; do not edit.

export builddir_name ?= /home/animesh/Desktop/A/breakpad/src/src/tools/windows/dump_syms/out
.PHONY: all
all:
	$(MAKE) -C ../../.. dump_syms dump_syms_unittest
