# This file is generated by gyp; do not edit.

export builddir_name ?= /home/animesh/Desktop/A/breakpad/src/src/tools/windows/converter/out
.PHONY: all
all:
	$(MAKE) -C ../../.. ms_symbol_server_converter
